name: Build and Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Windows x86_64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller gflzirc

      - name: Build with PyInstaller
        shell: bash
        run: python mk/build.py

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir -p upload_stage
          cp -r dist/GF1Alarm "upload_stage/GF1Alarm-win-x86_64"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GF1Alarm-win-x86_64
          path: upload_stage

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Artifacts
        run: |
          mkdir -p release_assets
          cd artifacts
          for dir in */; do
            dir=${dir%*/}
            zip_name="${dir}.zip"
            (cd "$dir" && zip -r "../../release_assets/$zip_name" .)
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*
          draft: false
          prerelease: false
          generate_release_notes: true